### ISSUE TITLE
Remove PDF from git repo

### ISSUE THREAD

**Issue by shwina** [linhbngo/teaching-PDC-using-python#1]
Because the PDF can be generated locally on each contributor's machine, it will only add noise and weight to version control. I would suggest removing it from the git repository:

~~~
$ git rm --cached main.pdf
$ git commit -m "Remove pdf from git repo"
~~~

Then, to the file `.gitignore`, add:

~~~
# .gitignore

main.pdf
~~~

**Comment by linhbngo** [comment]
Thanks Ashwin, I have removed the pdf and also added the file to gitignore.

**Comment by shwina** [comment]
Super! Thanks
